# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "C:/Users/user/Desktop/nisan/alex_replying_working_first_example_plus_aurora_forwarding_rx_1byte/.Xil/Vivado-19660-MSI/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7k325tfbv676-2
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    C:/Users/user/Desktop/nisan/alex_replying_working_first_example_plus_aurora_forwarding_rx_1byte/alex.srcs/sources_1/ip/gig_ethernet_pcs_pma_0
    C:/Users/user/Desktop/nisan/alex_replying_working_first_example_plus_aurora_forwarding_rx_1byte/alex.srcs/sources_1/ip/aurora_8b10b_0
    C:/Users/user/Desktop/nisan/alex_replying_working_first_example_plus_aurora_forwarding_rx_1byte/alex.srcs/sources_1/ip/clk_wiz_0
  } {
      C:/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      C:/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv
      C:/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -include {
    C:/Users/user/Desktop/nisan/alex_replying_working_first_example_plus_aurora_forwarding_rx_1byte/alex.srcs/sources_1/ip/gig_ethernet_pcs_pma_0
    C:/Users/user/Desktop/nisan/alex_replying_working_first_example_plus_aurora_forwarding_rx_1byte/alex.srcs/sources_1/ip/aurora_8b10b_0
    C:/Users/user/Desktop/nisan/alex_replying_working_first_example_plus_aurora_forwarding_rx_1byte/alex.srcs/sources_1/ip/clk_wiz_0
  } {
      C:/Users/user/Desktop/nisan/alex_replying_working_first_example_plus_aurora_forwarding_rx_1byte/.Xil/Vivado-19660-MSI/realtime/gig_ethernet_pcs_pma_0_stub.v
      C:/Users/user/Desktop/nisan/alex_replying_working_first_example_plus_aurora_forwarding_rx_1byte/.Xil/Vivado-19660-MSI/realtime/aurora_8b10b_0_stub.v
      C:/Users/user/Desktop/nisan/alex_replying_working_first_example_plus_aurora_forwarding_rx_1byte/.Xil/Vivado-19660-MSI/realtime/clk_wiz_0_stub.v
      C:/Users/user/Desktop/nisan/alex_replying_working_first_example_plus_aurora_forwarding_rx_1byte/alex.srcs/lib/arbiter.v
      C:/Users/user/Desktop/nisan/alex_replying_working_first_example_plus_aurora_forwarding_rx_1byte/alex.srcs/sources_1/arp.v
      C:/Users/user/Desktop/nisan/alex_replying_working_first_example_plus_aurora_forwarding_rx_1byte/alex.srcs/sources_1/arp_cache.v
      C:/Users/user/Desktop/nisan/alex_replying_working_first_example_plus_aurora_forwarding_rx_1byte/alex.srcs/sources_1/arp_eth_rx.v
      C:/Users/user/Desktop/nisan/alex_replying_working_first_example_plus_aurora_forwarding_rx_1byte/alex.srcs/sources_1/arp_eth_tx.v
      C:/Users/user/Desktop/nisan/alex_replying_working_first_example_plus_aurora_forwarding_rx_1byte/alex.srcs/sources_1/new/aurora_8b10b_0_AXI_TO_LL_EXDES.v
      C:/Users/user/Desktop/nisan/alex_replying_working_first_example_plus_aurora_forwarding_rx_1byte/alex.srcs/sources_1/new/aurora_8b10b_0_FRAME_CHECK.v
      C:/Users/user/Desktop/nisan/alex_replying_working_first_example_plus_aurora_forwarding_rx_1byte/alex.srcs/lib/axis_async_fifo.v
      C:/Users/user/Desktop/nisan/alex_replying_working_first_example_plus_aurora_forwarding_rx_1byte/alex.srcs/lib/axis_async_fifo_adapter.v
      C:/Users/user/Desktop/nisan/alex_replying_working_first_example_plus_aurora_forwarding_rx_1byte/alex.srcs/lib/axis_fifo.v
      C:/Users/user/Desktop/nisan/alex_replying_working_first_example_plus_aurora_forwarding_rx_1byte/alex.srcs/sources_1/axis_gmii_rx.v
      C:/Users/user/Desktop/nisan/alex_replying_working_first_example_plus_aurora_forwarding_rx_1byte/alex.srcs/sources_1/axis_gmii_tx.v
      C:/Users/user/Desktop/nisan/alex_replying_working_first_example_plus_aurora_forwarding_rx_1byte/alex.srcs/sources_1/eth_arb_mux.v
      C:/Users/user/Desktop/nisan/alex_replying_working_first_example_plus_aurora_forwarding_rx_1byte/alex.srcs/sources_1/eth_axis_rx.v
      C:/Users/user/Desktop/nisan/alex_replying_working_first_example_plus_aurora_forwarding_rx_1byte/alex.srcs/sources_1/eth_axis_tx.v
      C:/Users/user/Desktop/nisan/alex_replying_working_first_example_plus_aurora_forwarding_rx_1byte/alex.srcs/sources_1/eth_mac_1g.v
      C:/Users/user/Desktop/nisan/alex_replying_working_first_example_plus_aurora_forwarding_rx_1byte/alex.srcs/sources_1/eth_mac_1g_fifo.v
      C:/Users/user/Desktop/nisan/alex_replying_working_first_example_plus_aurora_forwarding_rx_1byte/alex.srcs/sources_1/fpga_core.v
      C:/Users/user/Desktop/nisan/alex_replying_working_first_example_plus_aurora_forwarding_rx_1byte/alex.srcs/sources_1/ip.v
      C:/Users/user/Desktop/nisan/alex_replying_working_first_example_plus_aurora_forwarding_rx_1byte/alex.srcs/sources_1/ip_arb_mux.v
      C:/Users/user/Desktop/nisan/alex_replying_working_first_example_plus_aurora_forwarding_rx_1byte/alex.srcs/sources_1/ip_complete.v
      C:/Users/user/Desktop/nisan/alex_replying_working_first_example_plus_aurora_forwarding_rx_1byte/alex.srcs/sources_1/ip_eth_rx.v
      C:/Users/user/Desktop/nisan/alex_replying_working_first_example_plus_aurora_forwarding_rx_1byte/alex.srcs/sources_1/ip_eth_tx.v
      C:/Users/user/Desktop/nisan/alex_replying_working_first_example_plus_aurora_forwarding_rx_1byte/alex.srcs/sources_1/lfsr.v
      C:/Users/user/Desktop/nisan/alex_replying_working_first_example_plus_aurora_forwarding_rx_1byte/alex.srcs/lib/priority_encoder.v
      C:/Users/user/Desktop/nisan/alex_replying_working_first_example_plus_aurora_forwarding_rx_1byte/alex.srcs/lib/sync_reset.v
      C:/Users/user/Desktop/nisan/alex_replying_working_first_example_plus_aurora_forwarding_rx_1byte/alex.srcs/sources_1/udp.v
      C:/Users/user/Desktop/nisan/alex_replying_working_first_example_plus_aurora_forwarding_rx_1byte/alex.srcs/sources_1/udp_checksum_gen.v
      C:/Users/user/Desktop/nisan/alex_replying_working_first_example_plus_aurora_forwarding_rx_1byte/alex.srcs/sources_1/udp_complete.v
      C:/Users/user/Desktop/nisan/alex_replying_working_first_example_plus_aurora_forwarding_rx_1byte/alex.srcs/sources_1/udp_ip_rx.v
      C:/Users/user/Desktop/nisan/alex_replying_working_first_example_plus_aurora_forwarding_rx_1byte/alex.srcs/sources_1/udp_ip_tx.v
      C:/Users/user/Desktop/nisan/alex_replying_working_first_example_plus_aurora_forwarding_rx_1byte/alex.srcs/sources_1/fpga.v
    }
      rt::read_vhdl -lib xpm C:/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top fpga
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter elaborateRtlOnlyFlow true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "C:/Users/user/Desktop/nisan/alex_replying_working_first_example_plus_aurora_forwarding_rx_1byte/.Xil/Vivado-19660-MSI/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
