# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/user/Desktop/mart2020/alex/alex.srcs/sources_1/ip/gig_ethernet_pcs_pma_0/gig_ethernet_pcs_pma_0.xci
# IP: The module: 'gig_ethernet_pcs_pma_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/user/Desktop/mart2020/alex/alex.gen/sources_1/ip/gig_ethernet_pcs_pma_0/gig_ethernet_pcs_pma_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'gig_ethernet_pcs_pma_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/user/Desktop/mart2020/alex/alex.gen/sources_1/ip/gig_ethernet_pcs_pma_0/synth/gig_ethernet_pcs_pma_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'gig_ethernet_pcs_pma_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/user/Desktop/mart2020/alex/alex.gen/sources_1/ip/gig_ethernet_pcs_pma_0/synth/gig_ethernet_pcs_pma_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'gig_ethernet_pcs_pma_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/user/Desktop/mart2020/alex/alex.srcs/sources_1/ip/gig_ethernet_pcs_pma_0/gig_ethernet_pcs_pma_0.xci
# IP: The module: 'gig_ethernet_pcs_pma_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/user/Desktop/mart2020/alex/alex.gen/sources_1/ip/gig_ethernet_pcs_pma_0/gig_ethernet_pcs_pma_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'gig_ethernet_pcs_pma_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/user/Desktop/mart2020/alex/alex.gen/sources_1/ip/gig_ethernet_pcs_pma_0/synth/gig_ethernet_pcs_pma_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'gig_ethernet_pcs_pma_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/user/Desktop/mart2020/alex/alex.gen/sources_1/ip/gig_ethernet_pcs_pma_0/synth/gig_ethernet_pcs_pma_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'gig_ethernet_pcs_pma_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
